// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson58986d13DecodeGithubComHtrandevGophermartInternalDomain(in *jlexer.Lexer, out *Accrual) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		switch key {
		case "order":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Order = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Status = AccrualStatus(in.String())
			}
		case "accrual":
			if in.IsNull() {
				in.Skip()
			} else {
				out.Accrual = float64(in.Float64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson58986d13EncodeGithubComHtrandevGophermartInternalDomain(out *jwriter.Writer, in Accrual) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"order\":"
		out.RawString(prefix[1:])
		out.String(string(in.Order))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"accrual\":"
		out.RawString(prefix)
		out.Float64(float64(in.Accrual))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Accrual) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson58986d13EncodeGithubComHtrandevGophermartInternalDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Accrual) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson58986d13EncodeGithubComHtrandevGophermartInternalDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Accrual) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson58986d13DecodeGithubComHtrandevGophermartInternalDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Accrual) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson58986d13DecodeGithubComHtrandevGophermartInternalDomain(l, v)
}
